### ISSUE TITLE
Create skills for Autogen

### ISSUE THREAD

**Issue by hackertron** [hackertron/LucidLoanMachine#1]

**Comment by AtHeartEngineer** [comment]
* TLSNotary
    * Using a relatively generic plugin, we could have the user login to their bank and go to their bank balance page, and then have the notary attest to that whole page without any information being redacted. The whole page can then be fed into chatgpt and it can parse what the bank balance is. The only thing that is critical that needs to be checked here is that the user went to the legit website (SSL/TLS verifies)
* ZKEmail
    * Walk user through how to copy and paste the raw email from whatever their email provider is.
* PDF with Signatures
* Smart Contract interaction
* EOA verification - prove the user owns an EOA

**Comment by hackertron** [comment]
## pdf verifications
- [ ]  read data from pdf
- [ ] verify pdf
- [x] ask user to answer questions 
- [ ] loan assistant/audit
- [ ] give out loan

**Comment by hackertron** [comment]
## zkemail verifications

- [x] guide user to paste raw email
- [x] verify the contents of the email
- [ ] loan assistant/audit
- [ ] give out loan
